#!/bin/sh
# Begin ~/.bash_login

clear
cat<<'EOF'
           _..._
         .'     '.
        /  _   _  \
        | (o)_(o) |
         \(     ) /
         //'._.'\ \
        //   .   \ \
       ||   .     \ \
       |\   :     / |
       \ `) '   (`  /_
     _)``".____,.'"` (_
     )     )'--'(     (
      '---`      `---`
EOF
echo "Hello $(whoami)"

echo "Current Date and Time"
echo $(date '+%A %B %d/%Y_%H:%M:%S')

# End ~/.bash_login
