#!/bin/bash
# Begin /etc/bashrc
# Written for Beyond Linux From Scratch

# System wide aliases and functions.

# System wide environment variables and startup programs should go into
# /etc/profile.
# Personal environment variables and startup programs should go into ~/.bash_profile.
# Personal aliases and functions should go into ~/.bashrc

# Provides colored /bin/ls and /bin/grep commands.  Used in conjunction
# with code in /etc/profile.

alias ls='ls --color=auto'
alias ll='ls -l'
alias grep='grep --color=auto'
alias DIR='du -h -BK'
alias EXEC='chmod -v +x'

# Provides prompt for non-login shells, specifically shells started
# in the X environment. [Review the LFS archive thread titled
# PS1 Environment Variable for a great case study behind this script
# addendum.]

NORMAL="\[\e[0m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
YELLOW="\[\e[1;33m\]"
ECODE='($?)'

if [[ -n "$SSH_CONNECTION" || -n "$SSH_CLIENT" || -n "$SSH_TTY" ]]; then
    # Running through SSH
    USER='\u@\h'
else
    USER='\u'
fi

if [[ $EUID == 0 ]] ; then
    if [[ ! /proc/1/root/. -ef / ]]; then
      CHROOT='(chroot)'
    fi
    PS1="${YELLOW}${CHROOT}${ECODE}${RED}${USER} [ ${NORMAL}\w${RED} ]# ${NORMAL}"
else
    PS1="${YELLOW}${ECODE}${GREEN}${USER} [ ${NORMAL}\w${GREEN} ]\$ ${NORMAL}"
fi

unset USER ECODE CHROOT RED GREEN NORMAL YELLOW

# End /etc/bashrc
