package:
    name: gsettings-desktop-schemas
    version: 48.0
    rel: 1
    archive: false
    delete: true

sources:
    - url: https://download.gnome.org/sources/gsettings-desktop-schemas/48/gsettings-desktop-schemas-48.0.tar.xz
      md5: e5721d5c378cb5fb4817943357b96ea5

prepare: |
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in &&
    meson setup ybuild --prefix=/usr --buildtype=release

build: |
    ninja -C ybuild

install: |
    ninja -C ybuild install

required:
    - glib2
