#!/bin/bash
install -v -m644 /etc/login.defs /etc/login.defs.orig &&

FUNCTION=(FAIL_DELAY FAILLOG_ENAB LASTLOG_ENAB MAIL_CHECK_ENAB OBSCURE_CHECKS_ENAB
  PORTTIME_CHECKS_ENAB QUOTAS_ENAB CONSOLE MOTD_FILE FTMP_FILE NOLOGINS_FILE ENV_HZ PASS_MIN_LEN
  SU_WHEEL_ONLY PASS_CHANGE_TRIES PASS_ALWAYS_WARN CHFN_AUTH ENCRYPT_METHOD ENVIRON_FILE)

for FUNC in ${FUNCTION[@]}
do
    sed -i "s/^${FUNC}/# &/" /etc/login.defs
done
